CREATE ALGORITHM = UNDEFINED
  DEFINER =`webseoindia`@`localhost`
  SQL SECURITY DEFINER VIEW `register_view` AS
  select
    `reg`.`index_id`              AS `index_id`,
    `reg`.`fb_id`                 AS `fb_id`,
    `reg`.`samyak_id`             AS `samyak_id`,
    `reg`.`matri_id`              AS `matri_id`,
    `reg`.`prefix`                AS `prefix`,
    `reg`.`terms`                 AS `terms`,
    `reg`.`email`                 AS `email`,
    `reg`.`password`              AS `password`,
    `reg`.`cpassword`             AS `cpassword`,
    `reg`.`cpass_status`          AS `cpass_status`,
    `reg`.`m_status`              AS `m_status`,
    `reg`.`profileby`             AS `profileby`,
    `reg`.`time_to_call`          AS `time_to_call`,
    `reg`.`reference`             AS `reference`,
    `reg`.`username`              AS `username`,
    `reg`.`firstname`             AS `firstname`,
    `reg`.`lastname`              AS `lastname`,
    `reg`.`gender`                AS `gender`,
    `reg`.`birthdate`             AS `birthdate`,
    `reg`.`birthtime`             AS `birthtime`,
    `reg`.`birthplace`            AS `birthplace`,
    `reg`.`tot_children`          AS `tot_children`,
    `reg`.`status_children`       AS `status_children`,
    `reg`.`education_level`       AS `e_level`,
    `reg`.`education_field`       AS `e_field`,
    `reg`.`part_edu_level`        AS `part_edu_level`,
    `reg`.`part_edu_field`        AS `part_edu_field`,
    `reg`.`edu_detail`            AS `edu_detail`,
    `reg`.`income`                AS `income`,
    `reg`.`monthly_sal`           AS `monthly_sal`,
    `reg`.`occupation`            AS `occupation`,
    `reg`.`emp_in`                AS `emp_in`,
    `reg`.`designation`           AS `designation`,
    `reg`.`other_caste`           AS `other_caste`,
    `reg`.`religion`              AS `religion`,
    `reg`.`caste`                 AS `caste`,
    `reg`.`subcaste`              AS `subcaste`,
    `reg`.`gothra`                AS `gothra`,
    `reg`.`star`                  AS `star`,
    `reg`.`moonsign`              AS `moonsign`,
    `reg`.`horoscope`             AS `horoscope`,
    `reg`.`manglik`               AS `manglik`,
    `reg`.`m_tongue`              AS `m_tongue`,
    `reg`.`height`                AS `height`,
    `reg`.`weight`                AS `weight`,
    `reg`.`b_group`               AS `b_group`,
    `reg`.`complexion`            AS `complexion`,
    `reg`.`bodytype`              AS `bodytype`,
    `reg`.`diet`                  AS `diet`,
    `reg`.`smoke`                 AS `smoke`,
    `reg`.`drink`                 AS `drink`,
    `reg`.`languages_known`       AS `languages_known`,
    `reg`.`address`               AS `address`,
    `reg`.`country_id`            AS `country_id`,
    `reg`.`state_id`              AS `state_id`,
    `reg`.`house_ownership`       AS `house_ownership`,
    `reg`.`living_status`         AS `living_status`,
    `reg`.`city`                  AS `city`,
    `reg`.`phone`                 AS `phone`,
    `reg`.`mobile`                AS `mobile`,
    `reg`.`contact_view_security` AS `contact_view_security`,
    `reg`.`disability`            AS `disability`,
    `reg`.`residence`             AS `residence`,
    `reg`.`father_name`           AS `father_name`,
    `reg`.`mother_name`           AS `mother_name`,
    `reg`.`father_living_status`  AS `father_living_status`,
    `reg`.`mother_living_status`  AS `mother_living_status`,
    `reg`.`father_occupation`     AS `father_occupation`,
    `reg`.`mother_occupation`     AS `mother_occupation`,
    `reg`.`profile_text`          AS `profile_text`,
    `reg`.`looking_for`           AS `looking_for`,
    `reg`.`family_origin`         AS `family_origin`,
    `reg`.`family_value`          AS `family_value`,
    `reg`.`family_details`        AS `family_details`,
    `reg`.`family_type`           AS `family_type`,
    `reg`.`family_status`         AS `family_status`,
    `reg`.`no_of_brothers`        AS `no_of_brothers`,
    `reg`.`no_of_sisters`         AS `no_of_sisters`,
    `reg`.`no_marri_brother`      AS `no_marri_brother`,
    `reg`.`no_marri_sister`       AS `no_marri_sister`,
    `reg`.`part_frm_age`          AS `part_frm_age`,
    `reg`.`part_to_age`           AS `part_to_age`,
    `reg`.`part_bodytype`         AS `part_bodytype`,
    `reg`.`part_diet`             AS `part_diet`,
    `reg`.`part_smoke`            AS `part_smoke`,
    `reg`.`part_drink`            AS `part_drink`,
    `reg`.`part_income`           AS `part_income`,
    `reg`.`part_emp_in`           AS `part_emp_in`,
    `reg`.`part_occupation`       AS `part_occupation`,
    `reg`.`part_designation`      AS `part_designation`,
    `reg`.`part_expect`           AS `part_expect`,
    `reg`.`part_height`           AS `part_height`,
    `reg`.`part_height_to`        AS `part_height_to`,
    `reg`.`part_complexion`       AS `part_complexion`,
    `reg`.`part_mtongue`          AS `part_mtongue`,
    `reg`.`part_religion`         AS `part_religion`,
    `reg`.`part_caste`            AS `part_caste`,
    `reg`.`part_manglik`          AS `part_manglik`,
    `reg`.`part_star`             AS `part_star`,
    `reg`.`part_edu`              AS `part_edu`,
    `reg`.`part_country_living`   AS `part_country_living`,
    `reg`.`part_state`            AS `part_state`,
    `reg`.`part_city`             AS `part_city`,
    `reg`.`part_resi_status`      AS `part_resi_status`,
    `reg`.`part_native_place`     AS `part_native_place`,
    `reg`.`hobby`                 AS `hobby`,
    `reg`.`hor_check`             AS `hor_check`,
    `reg`.`hor_photo`             AS `hor_photo`,
    `reg`.`photo_protect`         AS `photo_protect`,
    `reg`.`photo_pswd`            AS `photo_pswd`,
    `reg`.`video`                 AS `video`,
    `reg`.`video_approval`        AS `video_approval`,
    `reg`.`video_url`             AS `video_url`,
    `reg`.`video_view_status`     AS `video_view_status`,
    `reg`.`photo_view_status`     AS `photo_view_status`,
    `reg`.`photo1`                AS `photo1`,
    `reg`.`photo1_approve`        AS `photo1_approve`,
    `reg`.`photo2`                AS `photo2`,
    `reg`.`photo2_approve`        AS `photo2_approve`,
    `reg`.`photo3`                AS `photo3`,
    `reg`.`photo3_approve`        AS `photo3_approve`,
    `reg`.`photo4`                AS `photo4`,
    `reg`.`photo4_approve`        AS `photo4_approve`,
    `reg`.`photo5`                AS `photo5`,
    `reg`.`photo5_approve`        AS `photo5_approve`,
    `reg`.`photo6`                AS `photo6`,
    `reg`.`photo6_approve`        AS `photo6_approve`,
    `reg`.`photo7`                AS `photo7`,
    `reg`.`photo7_approve`        AS `photo7_approve`,
    `reg`.`photo8`                AS `photo8`,
    `reg`.`photo8_approve`        AS `photo8_approve`,
    `reg`.`reg_date`              AS `reg_date`,
    `reg`.`ip`                    AS `ip`,
    `reg`.`agent`                 AS `agent`,
    `reg`.`last_login`            AS `last_login`,
    `reg`.`status`                AS `status`,
    `reg`.`fstatus`               AS `fstatus`,
    `reg`.`logged_in`             AS `logged_in`,
    `reg`.`adminrole_id`          AS `adminrole_id`,
    `reg`.`franchised_by`         AS `franchised_by`,
    `reg`.`adminrole_view_status` AS `adminrole_view_status`,
    `reg`.`mobile_verify_status`  AS `mobile_verify_status`,
    `sta`.`state_name`            AS `state_name`,
    `cnt`.`country_name`          AS `country_name`,
    `rel`.`religion_name`         AS `religion_name`,
    `cst`.`caste_name`            AS `caste_name`,
    `ct`.`city_name`              AS `city_name`,
    `ct1`.`city_name`             AS `family_city`,
    `edu`.`edu_name`              AS `edu_name`,
    `elvl`.`e_level_name`         AS `education_level`,
    `efld`.`e_field_name`         AS `education_field`,
    `ocp`.`ocp_name`              AS `ocp_name`,
    `mt`.`mtongue_name`           AS `mtongue_name`,
    `dsg`.`desg_name`             AS `desg_name`
  from ((((((((((
      ((`register` `reg` left join `caste` `cst` on ((`reg`.`caste` = `cst`.`caste_id`))) left join `religion` `rel`
          on ((`reg`.`religion` = `rel`.`religion_id`))) left join `state` `sta`
        on ((`reg`.`state_id` = `sta`.`state_id`))) left join `country` `cnt`
      on ((`reg`.`country_id` = `cnt`.`country_id`))) left join `city` `ct`
      on ((`reg`.`city` = `ct`.`city_id`))) left join `city` `ct1`
      on ((`reg`.`family_origin` = `ct1`.`city_id`))) left join `education_detail` `edu`
      on ((`reg`.`edu_detail` = `edu`.`edu_id`))) left join `education_level` `elvl`
      on ((`reg`.`education_level` = `elvl`.`e_level_id`))) left join `education_field` `efld`
      on ((`reg`.`education_field` = `efld`.`e_field_id`))) left join `occupation` `ocp`
      on ((`reg`.`occupation` = `ocp`.`ocp_id`))) left join `mothertongue` `mt`
      on ((`reg`.`m_tongue` = `mt`.`mtongue_id`))) left join `designation` `dsg`
      on ((`reg`.`designation` = `dsg`.`desg_id`)))